### ISSUE TITLE
Feature request: Enable adding of attributes to the main parent tags

### ISSUE THREAD

**Issue by d-ratcliffe** [WPManageNinja/easy-code-manager#23]
I've had a request from a client to add some markup to a site for linked data. 

This needs adding as JS in a script tag but I would like to add the script tag with the type attribute to help google crawlers as follows:

<script type="application/ld+json">
...
<script>

Currently I don't believe this is possible as the main parent tags cannot be edited.

I think this would be a fantastic addition if possible!

**Comment by techjewel** [comment]
@d-ratcliffe You can just use html and write whatever you want and then print that on head / footer.

**Comment by d-ratcliffe** [comment]
Brilliant thanks for a quick response
